language: node_js

node_js:
   - node # will use latest node

script: # the build step
   - yarn build

before_script:
  - npm install -g --silent firebase-tools

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token $FIREBASE_TOKEN --non-interactive